name: shagf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
    
  firebase_core: ^3.1.1 
  firebase_auth: ^5.1.1 
  provider: ^6.1.5+1
  intl_phone_number_input: ^0.7.5
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_shagf.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F9F9F4"
  image: assets/logo_shagf.png
  android_12:
    color: "#F9F9F4"
    image: assets/logo_shagf.png
    

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
